# Exfat Linux kernel modules
#
obj-$(CONFIG_EXFAT_NOFUSE) += exfat.o
exfat-objs += exfat_core.o exfat_api.o exfat_blkdev.o exfat_cache.o exfat_super.o exfat_data.o exfat_global.o exfat_nls.o exfat_oal.o exfat_upcase.o
